config/routes.rb
Rails.application.routes.draw do
  get "main/index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :main, only: [ :index ]

  namespace :dog_ceo_api do
    resources :searches, only: [ :create ]
  end

  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dog_ceo_api/searches_controller.rb
module DogCeoApi
  class SearchesController < ::ApplicationController
    def create
      breed = search_params[:breed].strip.gsub(" ", "/").downcase

      if breed.blank?
        return render_flash_message_error("Breed cannot be blank")
      end

      case Client.random_image(breed:)
      in ::DogCeoApi::Client::Error => _error
        render_flash_message_error("Breed not found")
      in ::DogCeoApi::Client::Dog => dog
        render_dog_photo(dog)
      end
    end

    private

    def search_params
      params.require(:search).permit(:breed)
    end

    def render_dog_photo(dog)
      flash.now[:notice] = "Breed found!"

      render turbo_stream: [
        turbo_stream.update("flash", partial: "application/flash_messages"),
        turbo_stream.update(
          "dog-photo",
          partial: "main/photo",
          locals: { dog: }
        )
      ]
    end

    def render_flash_message_error(error)
      flash.now[:alert] = error

      render turbo_stream: [
        turbo_stream.update("dog-photo"),
        turbo_stream.update("flash", partial: "application/flash_messages")
      ]
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative"
    when "success" then "bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative"
    when "error" then "bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
    when "alert" then "bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative"
    else "bg-gray-100 border border-gray-400 text-gray-700 px-4 py-3 rounded relative"
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash-message <%= flash_class(type) %>">
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dog Ceo Fun" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col items-center">
      <h1 class="mb-4 text-4xl font-bold text-blue-600 md:text-5xl lg:text-6xl">
        DogCeoApi Fun
      </h1>

      <div id="flash">
        <%= render "application/flash_messages" %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>

app/views/main/_form.html.erb
<div class="mt-4 flex items-center justify-center space-x-6">
  <%= form_with url: dog_ceo_api_searches_path, scope: :search, method: :post, class: "space-y-4" do |form| %>
    <div class="w-full">
      <%= form.label :breed, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :breed, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <div>
      <%= form.submit "Submit", class: "mt-4 bg-blue-500 text-white py-2 px-4 rounded-md" %>
    </div>
  <% end %>

  <div data-controller="loading">
    <div data-loading-target="spinner"
      data-action="turbo:before-fetch-request@document->loading#show turbo:before-stream-render@document->loading#hide"
      class="hidden flex h-48 w-48 items-center justify-center bg-white bg-opacity-75">
      <div class="animate-spin rounded-full h-16 w-16 border-t-4 border-blue-500"></div>
    </div>

    <div id="dog-photo" data-loading-target="photo">
      <%= render partial: "main/photo", locals: { dog: nil }%>
    </div>
  </div>
</div>

app/views/main/_photo.html.erb
<%# locals: (dog: nil) %>

<% if dog %>
  <div>
    <h2 class="mb-4 text-2xl font-semibold text-gray-700 md:text-3xl lg:text-4xl bg-yellow-200 p-2 rounded-md border border-yellow-300 shadow-sm">
      <%= dog.breed.capitalize %>
    </h2>
    <figure class="w-48 h-48 border border-gray-300 rounded-md flex items-center justify-center">
      <%= image_tag(dog.photo_url, alt: "Dog photo", class: "object-cover w-full h-full rounded-md") %>
    </figure>
  </div>
<% end %>

app/views/main/index.html.erb
<%= render "form" %>